### ISSUE TITLE
Compatibility with TrainingPvP

### ISSUE THREAD

**Issue by Malachiel87** [BattlePlugins/BattleTracker#12]
When i run battletracker with trainingPvP and start and duel end it give this error each time. https://www.spigotmc.org/resources/trainingpvp-a-duel-plugin-1v1-2v2-party-vs-party-party-ffa-and-party-battle.5172/

11:13:49] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to BattleTracker v2.5.9.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6abac0c-9935adc]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6abac0c-9935adc]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:395) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:811) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6abac0c-9935adc]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
    at mc.alk.tracker.controllers.MessageController.getPvPMessage(MessageController.java:141) ~[?:?]
    at mc.alk.tracker.listeners.BTEntityListener.getPvPDeathMessage(BTEntityListener.java:287) ~[?:?]
    at mc.alk.tracker.listeners.BTEntityListener.ede(BTEntityListener.java:180) ~[?:?]
    at mc.alk.tracker.listeners.BTEntityListener.onPlayerDeath(BTEntityListener.java:66) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6abac0c-9935adc]
    ... 22 more

**Comment by Zach443** [comment]
I would test this out, but it's $10USD plugin. You should jump on IRC so I can maybe get a little more info on this.

**Comment by Zach443** [comment]
Link is dead or plugin doesn't exist anymore. Either way, it's a premium plugin so I don't want to jack with it. 

If someone sees this in the future and cares, drop by Discord and we will talk.

**Comment by Europia79** [comment]
So BattleTracker wants to provide GENERAL stat tracking options with the ability for plugins to hook into its API... Then we get a bunch of tickets like this and quite possibly have to hook into thousands of different plugins to account for all the weird shit they're doing.

You see the problem here is that the Maven build system that we use for BattleTracker is not going to allow any circular dependencies (and rightfully-so).

BattleTracker cannot do this any longer: Perform TWO different responsibilities in ONE plugin.

It needs to be TWO plugins.

One plugin provides the general API.
Second plugins can depend on this API & use it to provide general stat tracking from events.

**Comment by Malachiel87** [comment]
woah after 3 years? xD

**Comment by Europia79** [comment]
I don't know if I got the original email notification, sorry.

**Comment by Malachiel87** [comment]
anyway that plugin is died
