### ISSUE TITLE
Kill with hands cause errors

### ISSUE THREAD

**Issue by Malachiel87** [BattlePlugins/BattleTracker#13]
Killing with hands (unarmed) it cause this error on console also it don't output the custom messages in "air" section, but vanilllal one:
Error:

```
[14:08:27] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to BattleTracker v2.5.9.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-76236cb-9cd1111]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-76236cb-9cd1111]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:395) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-76236cb-9cd1111]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
    at mc.alk.tracker.controllers.MessageController.getPvPMessage(MessageController.java:141) ~[?:?]
    at mc.alk.tracker.listeners.BTEntityListener.getPvPDeathMessage(BTEntityListener.java:287) ~[?:?]
    at mc.alk.tracker.listeners.BTEntityListener.ede(BTEntityListener.java:180) ~[?:?]
    at mc.alk.tracker.listeners.BTEntityListener.onPlayerDeath(BTEntityListener.java:66) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor616.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-76236cb-9cd1111]
    ... 22 more
[14:08:27] [Server thread/INFO]: EthO1122 died
```

**Comment by Zach443** [comment]
What version of spigot are you using?

**Comment by Malachiel87** [comment]
spigot 1.8.8

**Comment by Malachiel87** [comment]
also got this warn sometimes
[11:50:31 WARN]: [Tracker] getPvPMessage, message node=pvp.rangeDeaths  args=davidos120:extramen:ItemStack{BOW x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, enchants={ARROW_DAMAGE=3}}}

**Comment by Redned235** [comment]
Resolved in rewrite. Closing.
