### ISSUE TITLE
Death on enderpearl

### ISSUE THREAD

**Issue by tangalbert919** [BattlePlugins/BattleTracker#20]
The following error occurs when I die using an enderpearl:
[16:17:33] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to BattleTracker v2.5.9.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:412) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:423) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:950) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:758) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.EntityEnderPearl.a(EntityEnderPearl.java:94) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.EntityProjectile.B_(EntityProjectile.java:167) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.EntityEnderPearl.B_(EntityEnderPearl.java:115) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1638) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1608) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1434) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:617) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at mc.alk.tracker.controllers.MessageController.getPvPMessage(MessageController.java:141) ~[?:?]
	at mc.alk.tracker.listeners.BTEntityListener.getPvPDeathMessage(BTEntityListener.java:285) ~[?:?]
	at mc.alk.tracker.listeners.BTEntityListener.ede(BTEntityListener.java:177) ~[?:?]
	at mc.alk.tracker.listeners.BTEntityListener.onPlayerDeath(BTEntityListener.java:63) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-Modified-EpicCraft.jar:git-Spigot-d5dfb24-ed8c725]
	... 20 more

**Comment by Redned235** [comment]
Resolved in rewrite. Closing.
