### ISSUE TITLE
PvE KDA throws an error when it's being tried to access

### ISSUE THREAD

**Issue by Jodsderechte** [BattlePlugins/BattleTracker#25]
[22:17:42] [ForkJoinPool.commonPool-worker-18/ERROR]: [BattleTracker] Could not prepare statement SELECT * FROM bt_pve_overall ORDER BY CAST(kd_ratio AS REAL) DESC LIMIT ?
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: kd_ratio)

Server Log
```
Console22:17:42
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.util.shaded.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:713) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.util.shaded.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:713) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.getStatement(SqlSerializer.java:327) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:222) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:206) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:195) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.TrackerSqlSerializer.lambda$getTopRecords$1(TrackerSqlSerializer.java:94) ~[BattleTracker.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1812) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189) ~[?:?]
ERROR22:17:42
[BattleTracker]: Could not execute query SELECT * FROM bt_pve_overall ORDER BY CAST(kd_ratio AS REAL) DESC LIMIT ?
Console22:17:42
java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.setQueryTimeout(int)" because "statement" is null
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:223) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:206) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:195) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.TrackerSqlSerializer.lambda$getTopRecords$1(TrackerSqlSerializer.java:94) ~[BattleTracker.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1812) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189) ~[?:?]
ERROR22:17:42
[BattleTracker]: Failed to load top records!
Console22:17:42
java.lang.NullPointerException: Cannot invoke "org.battleplugins.tracker.sql.SqlSerializer$ResultSetConnection.rs()" because "connection" is null
	at BattleTracker.jar/org.battleplugins.tracker.sql.TrackerSqlSerializer.lambda$getTopRecords$1(TrackerSqlSerializer.java:96) ~[BattleTracker.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1812) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189) ~[?:?]
```	
	
	Full stack trace:
	
	```
	[21:44:46] [ForkJoinPool.commonPool-worker-75/ERROR]: [BattleTracker] Could not prepare statement SELECT * FROM bt_pvp_overall ORDER BY CAST(kd_ratio AS REAL) DESC LIMIT ?
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: kd_ratio)
	at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.core.DB.throwex(DB.java:1150) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:132) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.core.DB.prepare(DB.java:264) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[sqlite-jdbc-3.46.1.3.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.util.shaded.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:713) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.util.shaded.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:713) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.getStatement(SqlSerializer.java:327) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:222) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:206) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:195) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.TrackerSqlSerializer.lambda$getTopRecords$1(TrackerSqlSerializer.java:94) ~[BattleTracker.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1812) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189) ~[?:?]
[21:44:46] [ForkJoinPool.commonPool-worker-75/ERROR]: [BattleTracker] Could not execute query SELECT * FROM bt_pvp_overall ORDER BY CAST(kd_ratio AS REAL) DESC LIMIT ?
java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.setQueryTimeout(int)" because "statement" is null
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:223) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:206) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.SqlSerializer.executeQuery(SqlSerializer.java:195) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.sql.TrackerSqlSerializer.lambda$getTopRecords$1(TrackerSqlSerializer.java:94) ~[BattleTracker.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1812) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189) ~[?:?]
[21:44:46] [ForkJoinPool.commonPool-worker-75/ERROR]: [BattleTracker] Failed to load top records!
java.lang.NullPointerException: Cannot invoke "org.battleplugins.tracker.sql.SqlSerializer$ResultSetConnection.rs()" because "connection" is null
	at BattleTracker.jar/org.battleplugins.tracker.sql.TrackerSqlSerializer.lambda$getTopRecords$1(TrackerSqlSerializer.java:96) ~[BattleTracker.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1812) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189) ~[?:?]
	```

**Comment by Jodsderechte** [comment]
this might be related. Got it in console right after (during) restart

```
ERROR10:58:07
[BattleTracker]: An error occurred when loading tracker pve.yml: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because "messagesSection" is null
Console10:58:07
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because "messagesSection" is null
	at BattleTracker.jar/org.battleplugins.tracker.feature.Killstreaks.load(Killstreaks.java:44) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.TrackerLoader.load(TrackerLoader.java:50) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.BattleTracker.loadTrackers(BattleTracker.java:440) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.BattleTracker.postInitialize(BattleTracker.java:206) ~[BattleTracker.jar:?]
	at BattleTracker.jar/org.battleplugins.tracker.BattleTrackerListener.onServerLoad(BattleTrackerListener.java:36) ~[BattleTracker.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:775) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
	```

**Comment by Jodsderechte** [comment]
After updating to the most recent version the pve tracker doesn't do anything anymore. It doesn't throw an error either but neither text replacements not the /pve commands do anything anymore
